{"uuid": "96faf95b-2b5b-45d2-9b94-9c7a2339cb19", "children": ["02383037-303e-4668-8ddb-dcdd5e5215e7"], "befores": [{"name": "driver", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.SessionNotCreatedException: Message: Could not create a session: You must enable the 'Allow Remote Automation' option in Safari's Develop menu to control Safari via WebDriver.\n\n", "trace": "  File \"/Users/chethangopal/Desktop/SwagSuace/.venv/lib/python3.11/site-packages/pluggy/_callers.py\", line 167, in _multicall\n    teardown.throw(outcome._exception)\n  File \"/Users/chethangopal/Desktop/SwagSuace/.venv/lib/python3.11/site-packages/_pytest/setuponly.py\", line 36, in pytest_fixture_setup\n    return (yield)\n            ^^^^^\n  File \"/Users/chethangopal/Desktop/SwagSuace/.venv/lib/python3.11/site-packages/pluggy/_callers.py\", line 103, in _multicall\n    res = hook_impl.function(*args)\n          ^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/Users/chethangopal/Desktop/SwagSuace/.venv/lib/python3.11/site-packages/_pytest/fixtures.py\", line 1122, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/Users/chethangopal/Desktop/SwagSuace/.venv/lib/python3.11/site-packages/_pytest/fixtures.py\", line 877, in call_fixture_func\n    fixture_result = next(generator)\n                     ^^^^^^^^^^^^^^^\n  File \"/Users/chethangopal/Desktop/SwagSuace/Tests/conftest.py\", line 27, in driver\n    driver = webdriver.Safari()\n             ^^^^^^^^^^^^^^^^^^\n  File \"/Users/chethangopal/Desktop/SwagSuace/.venv/lib/python3.11/site-packages/selenium/webdriver/safari/webdriver.py\", line 60, in __init__\n    super().__init__(command_executor=executor, options=options)\n  File \"/Users/chethangopal/Desktop/SwagSuace/.venv/lib/python3.11/site-packages/selenium/webdriver/remote/webdriver.py\", line 208, in __init__\n    self.start_session(capabilities)\n  File \"/Users/chethangopal/Desktop/SwagSuace/.venv/lib/python3.11/site-packages/selenium/webdriver/remote/webdriver.py\", line 292, in start_session\n    response = self.execute(Command.NEW_SESSION, caps)[\"value\"]\n               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/Users/chethangopal/Desktop/SwagSuace/.venv/lib/python3.11/site-packages/selenium/webdriver/remote/webdriver.py\", line 347, in execute\n    self.error_handler.check_response(response)\n  File \"/Users/chethangopal/Desktop/SwagSuace/.venv/lib/python3.11/site-packages/selenium/webdriver/remote/errorhandler.py\", line 229, in check_response\n    raise exception_class(message, screen, stacktrace)\n"}, "start": 1717189231674, "stop": 1717189231823}], "start": 1717189231674, "stop": 1717189231871}